### ISSUE TITLE
expected string

### ISSUE THREAD

**Issue by agilgur5** [zaach/jsonlint#119]

**Comment by prantlf** [comment]
You could add single quotes to the lexer and instead of recognising them as string declarators, you would just make the tokenisation failed. I did [something similar for JavaScript-like comments](https://github.com/prantlf/jsonlint/blob/master/src/jsonlint.l#L6), so that they could be either ignored, or reported by a better error message.

**Comment by agilgur5** [comment]
Oh cool, thanks for the suggestion @prantlf !

Good luck on the fork and hope it does well! I also maintain a [heavily updated fork of a library](https://github.com/agilgur5/react-signature-canvas) :)
