### ISSUE TITLE
Should accept a folder/glob as an argument

### ISSUE THREAD

**Issue by derekprior** [zaach/jsonlint#23]
I'd love to lint multiple json files in a single go, and get a report of each failure, but: `jsontlint project/**/*.json` doesn't seem to do the job. When linting multiple files it'd probably make sense to not output pretty-printed json when a file passes - simply return the errors.

What do you think?

**Comment by radek-holy** [comment]
Hello, the `find` command is not available on Windows, so to write a portable script that lints JSON files (e.g. an NPM script), one has to write/install a portable `find`. With the possibility to pass just file names, the task would be much simpler. And for the same reason, it would be nice if the glob expansion would be done by jsonlint and not a shell.

Would this argument change your mind? There is actually a lot of Node programs that accept globs already. That's why I think that the request is reasonable.

**Comment by keik** [comment]
+1

**Comment by zaach** [comment]
PRs would be considered.
