### ISSUE TITLE
Large (long) integers incorrectly parsed

### ISSUE THREAD

**Issue by ssgosh** [zaach/jsonlint#63]
Input to http://zaach.github.io/jsonlint/ : {"fooId":1111111111258928239}
Output:
{
  "fooId": 1111111111258928300
}

Somehow the 239 in the last 3 digits becomes 300. The input integer fits within 64 bits (long type in Java). The issue is reproducible with different values and it is always the last few digits which are different. This has not been an issue for small integers (2-3 digits).

Thanks!

**Comment by ssgosh** [comment]
Realized that this is a general javascript issue. Javascript represents numbers as floating-point numbers with 53-bit precision. As a workaround, I will use smaller integers in my code. 

I will leave this bug open for a possible implementation of jsonlint number parsing using [Biginteger ] (https://www.npmjs.com/package/big-integer) or some other library supporting large integers in javascript.

**Comment by tjayrush** [comment]
First-it's always rounded, so it seems that the 53-bit precision thing is correct. Second--it really should be fixed. I'm trying to use jsonlint in the blockchain space where the integers are frequently even bigger than fits in a 64-bit long. You should use some sort of big-int library to handle blockchain cases. It becomes more pressing when you realize that the numbers represent money in the blockchain space. People don't like loosing money, even if it millionths of a cent.

**Comment by prantlf** [comment]
The [specification does not limit the count of digits](https://tools.ietf.org/html/rfc7159#section-6) in integer parts of numbers. However, it tells the implementors, that they should keep to [IEEE 754](IEEE 754](https://en.wikipedia.org/wiki/IEEE_754-2008_revision) to produce an _interoperable JSON format_.

> This specification allows implementations to set limits on the range
and precision of numbers accepted.  Since software that implements
IEEE 754-2008 binary64 (double precision) numbers IEEE 754 is
generally available and widely used, good interoperability can be
achieved by implementations that expect no more precision or range
than these provide, in the sense that implementations will
approximate JSON numbers within the expected precision.

If your JSON input can contain numbers, which are not compatible with JavaScript, you can implement a [`reviver` for the `JSON.parse` method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#Parameters) to make it return.something else than `Number`. However, it will be your custom implementation for your application only. (If you want a round-tripping implementation, you will need to implement a [`replacer` for the `JSON.stringify` method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Parameters) too.)

It would be nice to be able to specify a `reviver` and `replacer` for the `parser` and `formatter` in `jsonlint` package too. Otherwise you have to use the built-in JSON parsing and formatting methods.

**Comment by ssgosh** [comment]
This bug seems to have been fixed. I tried the original example at https://jsonlint.com/

Input: `{"fooId":1111111111258928239}`
Output:
```json
{
	"fooId": 1111111111258928239
}
```

Hence I am closing this bug.
